name: Composite maven java test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Testing use of composite action
    steps:
      - uses: actions/checkout@v4
      - uses: nickej/actions-test/.github/actions/java-maven-build-composite@main
        with:
          java-version: 21