name: Deploy to test

on:
  workflow_dispatch:

jobs:
  build:  
    uses: nickej/actions-test/.github/workflows/build.yml@main

  deploy:
    runs-on: ubuntu-latest
    environment: test
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to test
        run: "echo Deploying to test, env value:${{vars.VARIABLE_NAME}}"
