name: Deploy to test

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    environment: test
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to test
        run: "echo Deploying to test, env value:${{vars.VARIABLE_NAME}}"
