name: Deploy to test

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    environment: test
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Tests
        run: echo Running tests
      - name: Build
        run: echo Building
